# Generated by Django 4.2.13 on 2024-07-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
