# Generated by Django 4.2.13 on 2024-07-07 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app2', '0002_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app2.contestant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app2.user')),
            ],
        ),
    ]
