# Generated by Django 4.2.13 on 2024-07-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app2', '0003_contestant_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
